config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'messages/index'
  
  root to: "messages#index"
  resources :messages, only: [:index, :create]
  resources :labors, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true

end

app/models/labor.rb
class Labor < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :wtime, optional: true
  

  validates :work_day, presence: true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  has_one_attached :image

  # validates :content, presence: true
  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/ }
end

app/models/w_time.rb
class WTime < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '8:00' },
    { id: 2, name: '8:30' },
    { id: 3, name: '9:00' },
    { id: 4, name: '9:30' },
    { id: 5, name: '10:00' },
    { id: 6, name: '10:30' },
    { id: 7, name: '11:00' },
    { id: 8, name: '11:30' },
    { id: 9, name: '12:00' },
    { id: 10, name: '12:30' },
    { id: 11, name: '13:00' },
    { id: 12, name: '13:30' },
    { id: 13, name: '14:00' },
    { id: 14, name: '14:30' },
    { id: 15, name: '15:00' },
    { id: 16, name: '15:30' },
    { id: 17, name: '16:00' },
    { id: 18, name: '16:30' },
    { id: 19, name: '17:00' },
    { id: 20, name: '17:30' },
=begin ,
    
    { id: 6, name: '' },
    { id: 7, name: '' },
    { id: 8, name: '' },
    { id: 9, name: '' },
    { id: 10, name: '' }
=end
  ]
  include ActiveHash::Associations
  has_many :labors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
  end
end

app/controllers/labors_controller.rb
class LaborsController < ApplicationController

  def new
    @labor = Labor.new
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
  end

  def create
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    @labor = Labor.new(labor_params)
    if @labor.save!
      redirect_to  new_labor_path
    else
      render action: :new
    end
  end

  def show
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    # @schedule = Labor.find(params[:id])
    @schedule = Labor.all
  end

  private
  def labor_params
    params.require(:labor).permit(:work_day, :start_time_id, :closing_time_id, :comment).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @user = User.all
    @message = Message.new
    @messages = Message.all
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
  end

  def new
  end

  def show
  end

  def create
    @wedays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    @user = User.all
    @messages = Message.all
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      render action: :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
  
end

# :image

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/labors/new.html.erb
<%= render "shared/header"%>
  <div class="labor_ti">出勤登録　<実装中バリデーション></div>
  <div class="labor_main">
    <%=form_with model: @labor, url: labors_path, local: true do |f|%>
      <h2>日付</h2>
      <div class="dayf">
        <%= f.date_field :work_day, class:"calendar" %>
      </div>
      <h2>時間</h2>
      <div class="time">
        <div>
          <%= f.collection_select(:start_time_id, WTime.all, :id, :name, {}, {class:"select-box", id:""}) %>
        </div>
          <h3>　〜　</h3> 
        <div>
          <%= f.collection_select(:closing_time_id, WTime.all, :id, :name, {}, {class:"select-box", id:""}) %>
        </div>
      </div>
      <h2>memo</h2>
      <div>
          <%= f.text_area :comment, class:"comment", id:"comment", placeholder:"comment" ,rows:"5" ,maxlength:"200" %>
      </div>
      <div>
        <%= f.submit "登録する" , class:"btn" %>
      </div>
    <%end%>
  </div>
<%= render "shared/footer2"%> 

      <%# <div class='input-day-wrap'> %>
        <%# <%= raw sprintf(
                    f.date_select(
                      :work_day,
                      class:'select-work_dayh',
                      id:"work_day-date",
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: 2020,
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %> 
      <%# <lavel>
        <input type="date" />
      </label> %>

app/views/labors/show.html.erb
<%= render "shared/header"%>
<div class="labor_ti">出勤確認　<未実装></div>

  <% @schedule.each do |schedule|%>
    <div>
    <%= schedule.work_day%>
    <%= schedule.start_time_id%>
    <%= schedule %>
    <%= schedule.closing_time_id%>
    <%= schedule.comment%>
    </div>
  <%end%>
  <%= WTime %>
  

<%= render "shared/footer2"%> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labor3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<%= render "shared/header"%> 
  <div class="main">
    <div class="side"> 
      <div class="side_list">
        <div class="member">Member</div>
        <% @user.each do |user|%>
          <li class='name_list'>
            <%=user.name%>
          </li>
        <%end%>
      </div>
    </div>
    <div class="chat_space">
      <div id="scroll-inner">
        <% if user_signed_in?%> 
        <% @messages.each do |messages|%>
          <%if messages.user_id == current_user.id%>
          <%# 自身のメッセ %>
            <div class='c_chat_cohesive'>
              <div class="chat_cohesive_inside">
                <div class="chat_top">
                  <div class="c_chat_name">
                  <%=messages.user.name%>
                  </div>
                  <div class="c_chat_time">
                  <%=messages.created_at.strftime("%Y-%m-%d %H:%M:%S")%>
                  </div>
                </div>
                <div class="c_chat_botom">
                <%=messages.content %>
                <%#= image_tag messages.image.variant(resize: '300x300'), class: 'message-image' if messages.image.attached? %>
                </div>
              </div>
            </div>
          <%else%>
          <%# 自分以外のメッセ %>
            <div class='chat_cohesive'>
              <div class="chat_cohesive_inside">
                <div class="chat_top">
                  <div class="chat_name">
                  <%=messages.user.name%>
                  </div>
                  <div class="chat_time">
                  <%=messages.created_at.strftime("%Y-%m-%d %H:%M:%S")%>
                  </div>
                </div>
                
                <div class="chat_botom">
                <%=messages.content%>
                </div>
              </div> 
            </div> 
          <%end%>
        <%end%> 
        <%end%>
      </div>
    </div>
  </div>
<%# <%= render "shared/footer1"%>  
<%# <%= render partial: "shared/footer1", locals: { message: @message }%> 
  <div class="footer">
    <div>
    </div>
    <%= link_to 'スケジュール提出', ' /labors/new',  class: "new_link" %>
    <div class="footer-form">
      <%= form_with model: @message, url: messages_path, class: 'message-form', local: true do |f| %>
        <div>
        <%= f.text_area :content, class:"text-form", placeholder:"text（1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
        <div>
        <%= f.submit "送信" ,class:"message-btn" %>
        </div>
<!--
        <div class="imagef">
          <label class="form-image">
          <span class="image-file">画像</span>
          <input type="file" class="hidden">
          </label>
-->
        </div>
      <%end%>
    </div>
  </div>

app/views/shared/_footer1.html.erb
<div class="footer">
  <div>
  </div>
  <h1>フッター１</h1>
  <div class="footer-form">
    <%= form_with model: @message, url: messages_path, class: 'message-form', local: true do |f| %>
      <div>
      <%= f.text_area :content, class:"text-form", id:"text-form", placeholder:"text（1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div>
      <%= f.submit "送信" ,class:"message-btn" %>
      </div>
    <%end%>
  </div>
</div>

app/views/shared/_footer2.html.erb
<div class="footer">
  <div class="giti"></div>
  <div class="gni"></div>
  <div class="gsan"></div>
  <div class="gyon"></div>
  <div class="ggo"></div>
  <div class="groku"></div>
  <div class="gnana"></div>
  <div class="ghati"></div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-left">
    <div class="hedtit">
      <div class="title">
      <%= link_to '< Labor >', root_path,  class: "title-logo" %>
      </div>
      <div class="day">
      <%= Date.today%> <%= @wedays[Date.today.wday] %>
      </div>
    </div>
  </div>

  <div class="header-rigth">
    <ul class='lists-right'>
      <% if user_signed_in?%> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <li><%= link_to current_user.name,  labor_path(current_user), class: "user-name" %></li>  
      <%else%>    
        <li><%= link_to '新規登録',  new_user_registration_path, class: "sign-up" %></li>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <%end%>  
    </ul>
  </div>
</div>